### PR TITLE
When using a custom Super class, it shall be used also in the return key management #298

### PR DESCRIPTION
**Pull request by GUL-**
Fix issue #298

### CODE REVIEW

**Comment by hackiftekhar** [comment]
You removed backward compatibility.

**Comment by GUL-** [comment]
Yes I did as your pod minimum version is ios8

**Comment by hackiftekhar** [comment]
But users is also able to drag and drop source code directly and target to lower versions too.

**Comment by GUL-** [comment]
Pod minimum version shall reflect the actual minimum version of your lib.
As I am targeting iOS 8 and newer I had warnings and thus decided to drop
compatibility code.
I will create a new dedicated branch for compatibility code deletion and
thus you will be able to accept my PR without dropping iOS 7 and lower
compatibility.
Is it ok for you?

**Comment by hackiftekhar** [comment]
I'll review your upcoming pull request. Thanks :)

**Pull request closed without merging**
