### PR TITLE
Do not consider keyboardDistanceFromTextField for scrollView contentInset

### PR DESCRIPTION
**Pull request by daniil108**
Fixed incorrect behavior when TextFields are on `scrollView` and using a custom `keyboardDistanceFromTextField`. Now scrolling consider `keyboardDistanceFromTextField`. @hackiftekhar please confirm it. If you have any suggestions on how this can be done differently and more correctly, please let me know.
 
Please see gifs
**Before:**
before

**After:**
after

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Hi, can you please share this demo with me?

**Comment by daniil108** [comment]
@hackiftekhar please see the demo, you can try reproduce the issue as on the gif
https://github.com/daniil108/IQKeyboardTest

ezgif-5-7d867e64633d

**Comment by witekbobrowski** [comment]
@daniil108 Thank you so much for solving this issue! I used the solution in my project and it now works as expected. Thank you!

@hackiftekhar Any chances of merging it anytime soon?

**Comment by hackiftekhar** [comment]
I will be checking this demo project soon @witekbobrowski.

**Comment by daniil108** [comment]
@hackiftekhar hey! What about this pull request? Do you have questions?

**Comment by hackiftekhar** [comment]
@daniil108 I checked the demo and found that you are correct. The behavior should be like your suggested changes. However, I have to make some more changes after yours to show the scroll indicator at correct position. I'll be merging your changes soon.

**Comment by hackiftekhar** [comment]
I cherry-pick your https://github.com/hackiftekhar/IQKeyboardManager/commit/c96e1355c426736b4e8a615e4412dad46691de64 and added some more changes here https://github.com/hackiftekhar/IQKeyboardManager/commit/6755980f8d17b710b620ef76fae238977ff2dc28 to fully fix the issue.

**Pull request closed without merging**
