### PR TITLE
Add support for Carthage

### LINKED ISSUE #213: Carthage support?
Would love to get carthage support for IQKeyboardManager - it would make it integrating into Swift projects much easier

### PR DESCRIPTION
**Pull request by AndrewSB**
closes #213

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Thanks for your pull request. Could you please let me know what what is my job to add it to Carthage?

**Comment by AndrewSB** [comment]
To add the project to Carthage all you need to do is merge my changes into the main repo and then create a new tagged release (probably v3.2.5)

**Comment by hackiftekhar** [comment]
Thanks Andew, I'll read about carthage and then definitely merge your pull request.

Thanks for your efforts.

**Comment by AndrewSB** [comment]
Cool! Let me know if you have any questions

**Comment by hackiftekhar** [comment]
BTW, I can see two 'IQKeyboardManager.xcodeproj' file now. One is mine inside 'KeyboardTextFieldDemo' directory and other one is on top of the repo. Can't we only keep one 'IQKeyboardManager.xcodeproj', because I if we have two .xcodeproj files on repo then users may confused at first time that which .xcodeproj should be open to see demo project. Hope you understand. Let me know what is best for us.

**Comment by AndrewSB** [comment]
Yes, that makes sense. I don't think that's reconcilable though because one is a proj with the source files while the other is one with a demo. 

I've seen other projects include an `xcworkspace` on the root level which has both the source xcodeproj and the demo xcodeproj, what do you think of doing something like that?

**Comment by hackiftekhar** [comment]
Adding workspace also be possible.

Can we achieve same result by creating a new target on demo project?

**Comment by AndrewSB** [comment]
Yes, but then it would make sense to move the demo xcodeproj out of the demo directory and up into the root directory. If that sounds good to you I can make those changes and submit a PR

**Comment by hackiftekhar** [comment]
Then give me some time. I'll restructure the project and will let you know when done.

**Comment by AndrewSB** [comment]
Sounds good @hackiftekhar, ping me back here when you're ready!

**Comment by hackiftekhar** [comment]
@AndrewSB Project restructured.

**Comment by hackiftekhar** [comment]
I received a pull request from @NicholasTD07 to support carthage. Are you ok to merge that.

**Comment by AndrewSB** [comment]
took a cursory looks, seems to be in order. Go ahead and merge it :+1:

**Comment by hackiftekhar** [comment]
Merged #278

**Comment by AndrewSB** [comment]
(and @toohotz)

**Comment by hackiftekhar** [comment]
Closed #213

**Pull request closed without merging**
