### PR TITLE
Fixed frame reset in the customized navigation pop animation

### PR DESCRIPTION
**Pull request by M-Quadra**
# Description

Prevent resetting frame in the customized navigation pop animation.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Can you please explain what exact changes you did in code?

**Comment by M-Quadra** [comment]
> Can you please explain what exact changes you did in code?

IQKeyboardManager's animation will cover UINavigationController‘s pop animation and change view's frame in the UIViewControllerAnimatedTransitioning.
So, I stop `-(void)restorePosition` when `self.rootViewController.view.layer.animationKeys.count > 0` to keep the pop animation effective.

As follows.

https://drive.google.com/file/d/1vrLYDF72R92AApMp6EZQMiUhXdA8nmU5/view?usp=sharing
https://drive.google.com/file/d/1hBQTN1HN2c1QNp73-QM5K_zXm0apnL8C/view?usp=sharing

https://github.com/M-Quadra/MQTransitionManager
https://github.com/M-Quadra/IQKeyboardManager

**Comment by hackiftekhar** [comment]
As per my understanding, IQKeyboardManager disturbing custom animation frame changes and positioning the controller to its original position.

Just to let you know, have you tried writing self.view.endsEditing(true) in `viewWillDisappear` (exactly when you are starting to dismiss the controller)?
I usually recommend resigning the keyboard when moving to another screen (in viewWillDisappear). This solves some basic problems with push/pop/present.

**Comment by hackiftekhar** [comment]
Hi @M-Quadra, I checked the demo project but still, I have difficulties understanding the issue. Can we have a little more discussion about the issue? I do not see different behavior as shown in your video.

**Comment by M-Quadra** [comment]
> As per my understanding, IQKeyboardManager disturbing custom animation frame changes and positioning the controller to its original position.
> 
> Just to let you know, have you tried writing self.view.endsEditing(true) in `viewWillDisappear` (exactly when you are starting to dismiss the controller)?
> I usually recommend resigning the keyboard when moving to another screen (in viewWillDisappear). This solves some basic problems with push/pop/present.

Yea, writing self.view.endsEditing(true) in viewWillDisappear can solve the animation problem.
At this time, the keyboard will show again.

If someone need keeping keyboard activating after pop animation canceled.
As follow:

write
```
-(void)restorePosition
{
    if (self.rootViewController.view.layer.animationKeys.count) return;
.......
```
in `IQKeyboardManager.m`

or use KVO and `[view.layer removeAnimationForKey:key];`

**Pull request closed without merging**
