### PR TITLE
Initializing IQKeyboardReturnKeyHandler with table view cell

### PR DESCRIPTION
**Pull request by bruno-hcr**
# Description

In project that I'm working, I need to handle done button, to validade the input in textfield.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by bruno-hcr** [comment]
Depending on architecture are you using in project, this way create 
unnecessary coupling in code. Don't you think so? For example, I need just create a key handler in my cell in MVP C architecture, but my cell access are just in my presenter of my view controller. I need to create dependency in my view controller, but my init content of my presenter is on coordinator.  
In this case, I need to create a new instance of presenter into my view controller to pass handler of view controller. My pull request intends to solve this type of problem. What do you think. Does it make any sense?

**Comment by hackiftekhar** [comment]
Can you please paste some of your code for better understanding your problem?

**Comment by hackiftekhar** [comment]
I mean where you are trying to initialize IQKeyboardReturnKeyHandler with cell? The example you shared looks like you are trying to initializa with a UIViewController.

**Comment by bruno-hcr** [comment]
Sorry, I fixed that, look the example again

**Comment by hackiftekhar** [comment]
@bruno-hcr You can write that like like this:-

```
let handler = IQKeyboardReturnKeyHandler()
handler.addResponderFromView(cell.contentView)
```

So why we'll need to introduce a new method for this?

**Comment by bruno-hcr** [comment]
Thanks's @hackiftekhar, I added your example in my `UITableViewCell` at `awakeFromNib()` method.

I tried debug textFieldShouldReturn

**Comment by hackiftekhar** [comment]
Assign IQKeyboardReturnKeyHandler delegate to self

**Comment by bruno-hcr** [comment]
@hackiftekhar I'm getting the following error: `Cannot assign value of type 'RechargeNumberCell' to type '(UITextFieldDelegate & UITextViewDelegate)?'`

**Comment by hackiftekhar** [comment]
You have to adopt `UITextFieldDelegate` and `UITextViewDelegate` protocol in your `DetailCell`

**Comment by bruno-hcr** [comment]
@hackiftekhar cool!
I resolve my business logic with other workaround, I used the `textFieldDidEndEditing` and verifying if keyboard is active... This way I believe that is is better way than adopt `UITextFieldDelegate` and `UITextViewDelegate`. Because this way I'll create some unnecessary dependencies in my code.
Thank you for support and answer my questions.
I'm getting close the pull request.

**Comment by hackiftekhar** [comment]
Thanks @bruno-hc

**Pull request closed without merging**
