### PR TITLE
[WIP] Swift 2 Support

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by AndrewSB** [comment]
Hey @hackiftekhar, having one issue. There's a private var called `_isTextFieldViewFrameChanged` I'm not sure if your latest commit was an attempt to get rid of it or if I somehow deleted the definition while rebasing.

Here's the error I'm getting right now: 
screen shot 2015-08-14 at 2 57 09 pm

How would you recommend resolving?

**Comment by hackiftekhar** [comment]
Np I'll resolve rest of the issues and commot back to beanch

**Comment by hackiftekhar** [comment]
Fixed and commit to Swift2.0.

**Comment by AndrewSB** [comment]
Awesome! Thanks @hackiftekhar

**Pull request merged**
