### PR TITLE
fix for ambiguous use of topMostController in Xcode9 GM Seed

### PR DESCRIPTION
**Pull request by alexwillingham**

### CODE REVIEW

**Comment by smilelifu** [comment]
My appearance, following the upgrade, iOS11, xcoe9, toobar, the button on both sides disappeared

**Comment by hackiftekhar** [comment]
The error was because the library having same method name for UIView category and UIWindow category, and UIWindow is a subclass of UIView.

The simple and better solution was to rename UIWindow method, so I did it. btw, thanks for the PR.

**Comment by alexwillingham** [comment]
Thanks @hackiftekhar

**Comment by hackiftekhar** [comment]
Thanks @alexwillingham for raising this issue anyway. Happy coding!

**Pull request closed without merging**
