### PR TITLE
fixed some issues with #96.

### PR DESCRIPTION
**Pull request by liulishuo**
Thank you for your excellent work ~ Now all my friends and colleagues use this keyboard manager.It is very useful but
sometimes next previous not working properly just like issues #96.Finally, i found some hidden views added into responderViews array may cause this case，so i add a few code,now it work well for me

### CODE REVIEW

**Comment by hackiftekhar** [comment]
I can see `IQUIView+Hierarchy.m`. I can see I added isHidden validation at line 145. Could you please clarify why it's needed again?

**Comment by liulishuo** [comment]
Thanks reply. if a view.isHidden == YES, we should never recursive it‘s subviews because it’s subviews‘s property "isHidden" may be "NO",then method "_IQcanBecomeFirstResponder"return "YES",
we may add a wrong view to responderViews array.

**Comment by hackiftekhar** [comment]
Ahh, Got You. Thanks. I need to write some more validation like alpha value. So I'll add it manually thanks

**Comment by liulishuo** [comment]
My pleasure,waiting for your good news

**Pull request closed without merging**
