### PR TITLE
Changes for Swift 2.0 and Xcode 7

### PR DESCRIPTION
**Pull request by mihirpmehta**
Add missing Info.plist file
remove unnecessary if condition for iOS 8
remove unnecessary switch condition (switch interfaceOrientation)
because interfaceOrientation is now always
UIInterfaceOrientation.Portrait

### CODE REVIEW

**Comment by hackiftekhar** [comment]
I think, we should keep compatibility for lower than iOS8 version, all the conditions and switch cases are maintained to make it compatible for lower than iOS8. Let me know your feedback.

**Comment by mihir-mehta** [comment]
As per apple statistics  92% users are on iOS 8 and above. It will be up to you ...

**Comment by hackiftekhar** [comment]
I'll update it to iOS8, when apple release an Xcode with minimum deployment target as iOS8. It's not good to drop support for lower version without any special reason. Currently some users are still on iOS7 and may be on iOS6. Also as I can see in Xcode7, minimum deployment target is iOS6. And do you know this library still works in iOS6 too.

**Comment by mihir-mehta** [comment]
That makes sense too ..

**Comment by hackiftekhar** [comment]
Could you please clarify what is missing related to Info.plist. I think this change have no relationship with iOS8 and it can be fix.

**Comment by kamaladafrica** [comment]
It is missing the file itself. 
For example, without it, Carthage is unable to compile because of dependency on Info.plist, that is missing.
I'm not an expert, but I think that removing the dependency on the file in the compilation process is better than add an empty file. 
Actually,  for the sake of simplicity, I added an empty Info.plist (like one in the commit) in order to make Carthage compile.

**Pull request closed without merging**
