### PR TITLE
Fix crash + remove all pre-iOS 8 #available checks

### PR DESCRIPTION
**Pull request by AndrewSB**
Was a little liberal with removing all of the `switch interfaceOrientation`s, after removing the if #available check XCode was telling me that the interfaceOrientation would always be portrait, so having the switches were useless and generating warnings.

Let me know what you think or if I should add those back

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Can't merge. It will affect those projects who still targeting iOS7.

**Comment by AndrewSB** [comment]
but the xcodeproj is targeting iOS 8, correct?

**Comment by hardikdevios** [comment]
@hackiftekhar i hope you should create branch for iOS 8 < devices because those are very less but still you have to manage in this code with lots of If conditions which doesn't require in the majority of the new devices because now a days, All are growing with iOS 9  so my suggestions to keep your code clean and  explore new APIs for upcoming OS'S with ease .. This is just a suggestion and i am open for discussion.

**Comment by AndrewSB** [comment]
would agree with @hardikdevios, I believe iOS 8 adoption is at 93% [source](https://developer.apple.com/support/app-store/). I think we can start phasing out updates for iOS 7 in favor of terser code and simpler implementation.

I can create a new a PR which just removes the crash, and maybe we can discuss the possibility of a phasing out iOS 7 support in a new issue/ PR?

**Comment by AndrewSB** [comment]
@hackiftekhar would love your input on this :smile:

**Comment by hackiftekhar** [comment]
Thanks @AndrewSB for providing a link for iOS 8 adoption rate. But you guys are thinking as **iOS Application Developer**, you are not as **Open Source Library Maintainer**. Open source libraries are used worldwide and we don't know who where and how it's going to use. That's why it's not great to drop support for lower deployment targets.

What I can do for you guys is You can fork this repo and drop support for iOS 7 and make your code available as cocoapods and I can put a note about your cocoapods in READ.md file.

**Comment by kwosu87** [comment]
I suggest you to consider the way removing iOS8 warnings.(it's 5 warnings!) As a **Open Source Library Maintainer** you want to people to use this as mush as they can, but in my opinion, people would consider first that this open source is clean and stable(not having errors, warnings, bugs). This library is **AWESOME**, but it makes me painful that always see 5 warnings in my xcode project. 

**Cocoapods** is developing new release but they still have bugs and not stable. There is no way removing that warnings now. This is why I suggest my opinion. No offense :)

**Comment by hackiftekhar** [comment]
@kwosu87 There is no errors or bugs with the pre-ios checks, that's 5 warning messages only and will not break anything. If it does break anything then I can think about migrating to iOS 8. Otherwise No.

**Comment by hardikdevios** [comment]
@kwosu87 +1 mate @hackiftekhar it not about 5 Warnings but sometime due to that warning we missed some important warnings which we need to resolve as an developer in our code.

As **iOS Dev** we don't want any warnings  because Todays warnings are tomorrows errors.
As **Open Source Lib maintainer** you are right but at some point you have to think about for creating different  version Like 
* **4.0 to only support for iOS 9 and iOS 8**
* **3.0 will support all which is current version**.

This will give you so many advantages to explore new API's in **4.0 version** without affecting **3.0 version** 
And in this case there will be no warnings for deployment target for **8.0 version.**

Otherwise it will create so many warnings for upcoming version and minimum deployment target is going to be 9.0 very soon as an current adoption rate of iOS devices.

Your have developed a Greatest LIB and it is default in each Podfile so we want this Lib neat and clean. Thanks Bro :+1:

**Comment by hackiftekhar** [comment]
That's a great suggestion to point-out different versions like *3.3.6 is the last supported version for iOS 7*. I think this will do the trick. I'll do some research with podspec https://guides.cocoapods.org/syntax/podspec.html if they allow to set minimum deployment target version of the pod. So if someone set minimum deployment target to 7.0 then 7.0 supported version should install and if someone set minimum deployment target to 8.0 then 8.0 supported version should install automatically.

**Comment by AndrewSB** [comment]
@hackiftekhar that sounds awesome :smile: projects like https://github.com/ReactiveX/RxSwift have done something similar I believe with setting a final release that supported a lower iOS version and then moving master onto iOS 8+

**Comment by AndrewSB** [comment]
@hackiftekhar had a chance to look yet? Do you want me to open a new PR to track this feature or do you want to just reopen this one?

**Comment by hackiftekhar** [comment]
I'll do a last push for iOS 7 users in next 2-3 days. After that I'll drop iOS 7 support and will push another version with iOS 8 as minimum deployment target version in next 2-3 days.

**Comment by AndrewSB** [comment]
sounds great!

**Comment by hardikdevios** [comment]
@hackiftekhar Thanks bro for your awesome support , **Happy Coding :+1: **

**Comment by hackiftekhar** [comment]
Now library support iOS 8 as minimum deployment target. Will release 4.0.0 in couple of days via cocoapods.

**Comment by hardikdevios** [comment]
@hackiftekhar Any Update bro for **4.0.0 version** pod ?

**Comment by hackiftekhar** [comment]
It is expected to release in weekends probably on 13th Feb.

**Comment by hackiftekhar** [comment]
**4.0.0 version pod** has been released today.

**Comment by kwosu87** [comment]
Thank you for you effort!

**Comment by hardikdevios** [comment]
@hackiftekhar you the best , finally 0 warnings  :+1:

**Pull request closed without merging**
