### PR TITLE
Added closure for handle property movedDistance

### PR DESCRIPTION
**Pull request by daniil108**
# Description

Added closure for handle property movedDistance

### CODE REVIEW

**Comment by Zyoma108** [comment]
@hackiftekhar hey! Can you review this improvement and merge if possible? It could be useful for me too.
Thanks.

**Comment by hackiftekhar** [comment]
This will help @Zyoma108 however we need to do same kind of changes in Objective-C code also. Can you please also do the same changes in Objective-C code as well?

**Comment by artFintch** [comment]
> This will help @Zyoma108 however we need to do same kind of changes in Objective-C code also. Can you please also do the same changes in Objective-C code as well?

Hello @hackiftekhar! I done that right now. Can you check it?

**Comment by hackiftekhar** [comment]
Looks good now!

**Pull request merged**
