### PR TITLE
fix crash: -[UILabel setInputAccessoryView:]: unrecognized selector sent on iOS8.4

### PR DESCRIPTION
**Pull request by dake**
fix crash: -[UILabel setInputAccessoryView:]: unrecognized selector sent on iOS8.4

### CODE REVIEW

**Comment by hackiftekhar** [comment]
Could you please let me know what line exactly cause the problem, because I can see you just restructure some code, but didn't do anything which change library logic.

**Comment by dake** [comment]
To prevent unrecognized selector crash, I added "&& [self respondsToSelector:@selector(setInputAccessoryView:)]"  in method -_IQcanBecomeFirstResponder, line 147.

**Comment by hackiftekhar** [comment]
Could you please let me know why this was crashing because I'm not calling setInputAccessoryView where you wrote conditions. It looks like it's specially for your project only. Right?

**Comment by dake** [comment]
Hi, the `setInputAccessoryView:` method was called in `addToolbarIfRequired` method  and `removeToolbarIfRequired` method, while UIViews return by `responderSiblings` may be a UILabel...

**Comment by hackiftekhar** [comment]
Nope, it will only return the uiview's, which 'canBecomeFirstResponder', so UILabel will never return in responderSiblings.

**Comment by dake** [comment]
@hackiftekhar you know, there may be some third subclasses of UILabel, they may override 'canBecomeFirstResponder' to return YES for some reason. It did happen, but UILabel or it's subclass do not implement 'setInputAccessoryView:' , so crash happened.

**Comment by hackiftekhar** [comment]
If any third party library implement and return canBecomeFirstResponder, then it's library responsibility to accept inputView and inputAccessoryView.

**Comment by hackiftekhar** [comment]
For extra care, now I added `setInputAccessoryView:` validations.

**Pull request closed without merging**
