### PR TITLE
only animate when UI kit allows

### PR DESCRIPTION
**Pull request by bj97301**
# Description
this will allow ui test to run faster

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by hackiftekhar** [comment]
@bj97301 Looks good, but we have to make same changes in Obj-C code also. Can you please update your PR?

**Comment by bj97301** [comment]
Can do. Not at work yet so it will be a few hours.

**Comment by bj97301** [comment]
Sorry it took so long.  Done now.

**Comment by hackiftekhar** [comment]
Thanks :)

**Comment by bj97301** [comment]
No problem 😁

**Pull request merged**
