### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by NicholasTD07**
* This PR adds Carthage support for the IQKeyboardManagerSwift framework.
* It also makes the necessary class `IQKeyboardManager` and also vars`enable`, `sharedManager` public to be exposed in the framework. I am already using it in my private project. :D
* And it fixes typo in `IQKeybordManagerSwift` (missing `a` in `keyboard`)

However, there's one small issue: Because the way Carthage uses xcode project file to build frameworks. I have to move `Demo.xcodeproj` into `Demo/`. I fixed almost all path changes in the project file. But there's one error. Basically Xcode is saying it couldn't find the `info.plist` file in `CopyPlist` phase. I just couldn't find where I can fix it.

PS.

I have to say, it's awesome and exciting to see that how keyboard is being managed automatically with only one line of code, such an easy thing! Thank you very much for your hard work! :)

### CODE REVIEW

**Comment by hackiftekhar** [comment]
I'm ok with writing 'public' with `sharedManager` method and `enable` property, even I'll mark all required properties as public. But could you please let me know why you wrote public with gesture delegate methods, is it really necessary?

**Comment by NicholasTD07** [comment]
Yes. Otherwise Xcode won't compile because of this error: 

/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift:428:11: Method 'gestureRecognizer(_:shouldReceiveTouch:)' must be declared public because it matches a requirement in public protocol 'UIGestureRecognizerDelegate'

**Comment by toohotz** [comment]
@NicholasTD07 is correct, @hackiftekhar  I recently packaged your source files similar to how Nic did here and I instead chose to mark those methods with private instead of public as it wouldn't make much sense to have them exposed (Xcode automagically suggesting public here wouldn't be the best bet).  

image

This compiles fine btw so aside from the merge conflicts just change the func types and you should be good to go (I can't edit your PR). :+1:

**Comment by hackiftekhar** [comment]
Merged #278

**Pull request merged**
